POST https://localhost:5001/api/account/balances
Accept: text/plain
Content-Type: application/json

{
    "ids": [
        "3087e02a-b169-4b2c-8feb-03dac40bf217", 
        "61b09de2-d15b-44e3-b35c-7342a9a57e43"
    ]
}
