POST https://localhost:5001/api/account/balances
Content-Type: application/json

{
    "ids": [
        "cca9de61-3de6-4a9a-94e7-a72d806e07da", 
        "dbf31c29-2418-49f9-a543-847054c4822a"
    ]
}
