POST https://localhost:5001/api/account/debit
Accept: text/plain
Content-Type: application/json

{
  "to": "c693897e-f6d5-46a8-bc6c-2131c8124382",
  "from": "4273c30a-b717-4dab-92f1-c40f90b17760",
  "description": "Transfer",
  "time": "2021-10-14T19:37:40.364Z",
  "amount": 50
}